---
- name: all hosts configuration
  hosts: gcp_items__u_controllers__
  become: yes
  gather_facts: True

  tasks:
  - name: download etcd
    get_url:
      url: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
      dest: /tmp/etcd.tar.gz
  - name: extract
    unarchive:
      src: /tmp/etcd.tar.gz
      dest: /tmp
      remote_src: yes
  - name: copy
    shell: cp -f /tmp/etcd-v3.3.9-linux-amd64/etcd* /usr/local/bin/
  - name: mkdir
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - /etc/etcd
      - /var/lib/etcd

  - name: copy certs
    copy:
      src: "{{ item }}"
      dest: /etc/etcd/
    with_items:
      - ../../certs/certs/ca.pem
      - ../../certs/certs/kubernetes-key.pem
      - ../../certs/certs/kubernetes.pem
    tags: ["certs"]

  - name: copy systemd
    template:
      src: etcd.service.j2
      dest: /etc/systemd/system/etcd.service

  - name: start etcd
    service:
      name: etcd
      enabled: yes
      state: started
