---
- name: deploy gitlab
  hosts: gcp_items__u_gitlab__
  become: true

  tasks:
    - name: prepare dirs
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs
      tags: deploy

    - name: docker-compose template
      template:
        src: files/docker-compose.yml.j2
        dest: /srv/gitlab/docker-compose.yml
      tags: deploy

    - name: starting gitlab
      shell: cd /srv/gitlab && docker-compose up -d
      tags: deploy
