---
- name: Add docker repository
  yum_repository:
    name: docker-ce
    description: Docker-CE
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker packages
  yum:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

